# serverless.yml

service: redditByEmail

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  pollReddit:
    handler: db/pollReddit.handler
  sendEmails:
    handler: server/email.handler
    events:
      - http:
          path: admin/sendEmails
          method: get
          cors: true
  apiServer:
    handler: server/index.handler
    events:
      - http:
          path: api/posts
          method: get
          cors: true
      - http:
          path: api/users
          method: post
          cors: true
      - http:
          path: unsubscribe
          method: get
          cors: true

plugins:
  - serverless-offline
