# serverless.yml

service: redditByEmail

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  pollReddit:
    handler: db/pollReddit.handler
    events:
      - schedule:
        name: send-emails-daily
        cron: cron(10 6 * * ? *)
  sendEmails:
    handler: server/email.handler
  apiServer:
    handler: server/index.handler
    events:
      - http:
          path: api/posts
          method: get
          cors: true
      - http:
          path: api/users
          method: post
          cors: true
